Prefix MSL mod function name to avoid clash in Storm (#1892)
Using a `ND_modulo_vector2FA` node in a material causes the shader code generated by Storm to fail to compile when using Metal.

```
 > usdview mod_bug.usda
Warning: in _ValidateCompilation at line 229 of ../../pxr/imaging/hdSt/glslProgram.cpp -- Failed to compile shader (FRAGMENT_SHADER): program_source:3055:33: error: no matching function for call to 'mod'
    vec2 modulo_vector2FA_out = mod(multiply_vector2_out, modulo_vector2FA_in2);
                                ^~~
program_source:136:3: note: candidate template ignored: deduced conflicting types for parameter 'T' ('float2' (vector of 2 'float' values) vs. 'float')
T mod(T y, T x) { return fmod(y, x); }
  ^

Warning: in _ValidateCompilation at line 229 of ../../pxr/imaging/hdSt/glslProgram.cpp -- Failed to compile shader (FRAGMENT_SHADER): program_source:4312:33: error: no matching function for call to 'mod'
    vec2 modulo_vector2FA_out = mod(multiply_vector2_out, modulo_vector2FA_in2);
                                ^~~
program_source:136:3: note: candidate template ignored: deduced conflicting types for parameter 'T' ('float2' (vector of 2 'float' values) vs. 'float')
T mod(T y, T x) { return fmod(y, x); }
  ^

ERROR: Usdview encountered an error while rendering.
	Error in '&pxrInternal_v0_24__pxrReserved__::HdSt_DrawBatch::_GetDrawingProgram' at line 408 in file ../../pxr/imaging/hdSt/drawBatch.cpp : 'Failed to compile shader for prim /Root/Geo/Cube.'
```
[mod_bug.zip](https://github.com/user-attachments/files/15894967/mod_bug.zip)

What's happening here is that Storm declares `T mod(T y, T x) { return fmod(y, x); }` earlier in the shader code, so the MaterialX defined Metal code for `mod()` isn't seen by the compiler.

By just renaming `mod()` to `mx_mod()` in the Metal source code provided by MaterialX, we avoid this name conflict.  Using this `mx_` "namespace" seems like a reasonable, pragmatic solution.

Moving the `mx_mod()` function outside of the `#ifdef __DECL_GL_MATH_FUNCTIONS__` guard ensures it's always used.  I think previously outside of the Storm context Metal may have been using the built in `mod()` call which doesn't follow the same math. (see https://stackoverflow.com/questions/41169747/solving-odd-behavior-re-glsl-metal-shader-unintentional-coordinate-flipping)