Fix Monolithic build on Windows (#1872)
Configure MaterialX with MATERIALX_BUILD_MONOLITHIC=ON on Windows, building this with with VS2022 causes couple issues:
1. error C1128: number of sections exceeded object file format fixed by adding /bigobj flag
2. Linker error from MaterialX_v1_39_0::OiioImageLoader::saveImage() fixed by muting OiioImageLoader using MATERIALX_BUILD_OIIO