With the latest VS2019 16.7 release, MaterialX fails to build (with errors below). (#962)
Looks like this is caused by the internal changes from vs2019 16.6 to 16.7 release.
MaterialX\source\MaterialXCore\Element.cpp(753,32): error C2039: 'inserter': is not a member of 'std'